title: Ajinkya Dhamnaskar
description: My Personal Blog
author: Ajinkya Dhamnaskar
logo: /static/img/avatar1.jpg
github: https://github.com/ajinkya-dhamnaskar
about: Master Student and Reserarch Assistant

baseurl: ""
url: "https://codeasashu.github.io/hcz-jekyll-blog"

disqus_shortname: ajinkyakd
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
